Sprint 1
MYiLA/middle.messenger.praktikum.yandex pull request #2
Opened 2023-04-06 23:42 UTC by MYiLA

2023-04-07 11:16 UTC, podlovchenko requested changes
Привет, в целом все хорошо, но есть некоторые замечания, оставила в коде, также сейчас при запуске сервера на express отдается строка 'index.html', необходимо отдавать файл

2023-04-07 11:16 UTC, podlovchenko commented on .gitignore
> +.parcel-cache
В проекте в некоторых файлах есть ошибка EOF
Для git важно наличие пустой строки в конце файла
https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

2023-04-07 11:16 UTC, podlovchenko commented on package.json
> +    "express": "^4.18.2",
В devDependencies указывается то, что необходимо для сборки и разработки приложения, в dependencies то, что необходимо непосредственно для работу приложения (express)

2023-04-07 11:16 UTC, podlovchenko commented on src/components/chat-list/chat-list.scss
> +  padding-bottom: 20px;
Можно использовать форму

padding: 20px 10px;

2023-04-07 11:16 UTC, podlovchenko commented on src/components/start-nav/start-nav.scss
> +  ul {
Лучше использовать классы, а не теги
Статья на эту тему https://frontstuff.io/you-need-to-stop-targeting-tags-in-css

2023-04-07 11:16 UTC, podlovchenko commented on src/server.js
> +const port = 3000;
Часто требуется возможность получить порт снаружи скрипта, не изменяя код, это можно сделать через переменное окружение:
process.env.PORT || PORT;
https://nodejs.org/dist/latest-v8.x/docs/api/process.html

2023-04-07 11:16 UTC, podlovchenko commented on src/common/settings.js
> +export const commonSettings = {
Это где-то используется?

2023-04-07 14:39 UTC, MYiLA commented on src/components/chat-list/chat-list.scss
> +  padding-bottom: 20px;
расписать на 4 разных свойства удобнее. Например конкретно в этом месте я не учла скроллбар, поэтому чейчас правый паддинг увеличила 
![image](https://user-images.githubusercontent.com/48839981/230627271-21f845c2-6790-409b-a4e9-a779caeb88ab.png)

2023-04-08 10:37 UTC, podlovchenko commented
Спасибо за оперативные правки, работу принимаю)

2023-04-08 12:10 UTC, merged